---
version: "3.2"
services:
  hubot:
    build: .
    # image: mohemohe/kokorobot:latest
    env_file: .env
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - hubot-nodemodules:/kokorobot/node_modules
      - type: mount
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:8080/"]
    restart: on-failure
  mongodb:
    container_name: hubot-mongodb
    image: mongo:3.6
    networks:
      - default
    volumes:
      - type: volume
        source: mongo-db
        target: /data/db
      - type: volume
        source: mongo-configdb
        target: /data/configdb
    restart: on-failure
volumes:
  hubot-nodemodules:
  mongo-db:
  mongo-configdb:
networks:
  default:
